# sheets config
sheetsId: 1hkynZs2fyTYpTCzA4fISg2vT7pwTpui7H4DDGwzFmzM
sheets:
  categories: 1210882748
  world: 0
  character: 1931742902
  prompts: 1378486483
  plot: 578448559
  ttrpg: 973338377

# file config
files:
  categories: categories.csv
  character: character.csv
  world: world.csv
  prompt: prompts.csv
  plot: plot.csv
  ttrpg: ttrpg.csv

help:
  -
    name: categories
    alts: [cats]
    usage: categories [filter]
    desc: Displays available categories, and allows you to filter by command
  -
    name: update
    alts: [download]
    usage: update
    desc: Updates questions to reflect the Google Sheet (developers only)
  -
    name: wbc
    alts: [worldbuilding]
    usage: wbc <filter>
    desc: Gives you a worldbuilding question
  -
    name: cbc
    alts: [character]
    usage: cbc <filter>
    desc: Gives you a character question
  -
    name: prompt
    alts: [prompts]
    usage: prompt <filter>
    desc: Gives you a writing prompt
  -
    name: pbc
    alts: [plot, sbc]
    usage: pbc <filter>
    desc: Gives you plot/structure-related questions
  -
    name: ttrpg
    alts: [rpg]
    usage: ttrpg <filter>
    desc: Gives you questions for building a ttrpg!
  -
    name: roll
    alts: [random]
    usage: roll <max>
    desc: Gives you a random number between 1 and `max` inclusive (default 6)
  -
    name: credits
    alts: []
    usage: credits
    desc: Credits for the bot

credits:
  Coding: 
    - snailmusic
  Questions: 
    - solariscrescent
    - snailmusic
    - killrbagel
    - celestine.
  Organization:
    - solariscrescent
    - snailmusic
  Prompts:
    - killrbagel
    - solariscrescent
    - https://writing-prompt-s.tumblr.com/
    - https://blog.reedsy.com/creative-writing-prompts/
    - https://presidentbttrflyfreak.tumblr.com/post/174722599040/heartbreaksad-dialogue-prompts
  Art:
    - solariscrescent
  Hosting:
    - [Railway](https://railway.com)

reloadAllowed: 
  - "260917329414586368"
  - "282909571054305282"
  - "728451464007254026"
